const ARCHIVE_COLLECTION_ID = "37729680";
const INBOX_COLLECTION_ID = "9785277";
const NEWSLETTER_COLLECTION_ID = "43141101";
const UNSORTED_COLLECTION_ID = "-1";

export {
  INBOX_COLLECTION_ID,
  ARCHIVE_COLLECTION_ID,
  NEWSLETTER_COLLECTION_ID,
  UNSORTED_COLLECTION_ID,
};
